### ISSUE TITLE
Devoxx2019 demo doesn't build

### ISSUE THREAD

**Issue by yregaieg** [flowable/flowable-examples#8]
Hi guys,

It seems that the demo from devoxx2019 was made using a snapshot version, and even though I cloned flowable/flowable-engine @ master and built that locally, I am still unable to compile the demo project and keep getting this error :

```
[ERROR] Failed to execute goal on project event-demo-common: Could not resolve dependencies for project org.flowable:event-demo-common:jar:0.0.1-SNAPSHOT: Failure to find org.flowable:flowable-spring-boot-starter:jar:6.5.0.event-SNAPSHOT in https://..... was cached in the local repository, resolution will not be reattempted until the update interval of .... has elapsed or updates are forced -> [Help 1]
```

**Comment by tijsrademakers** [comment]
Hi,

We are working hard to get everything on master, but for now you have to build it from a branch:

https://github.com/flowable/flowable-engine/tree/eventbus_dev

**Comment by yregaieg** [comment]
Alright, thanks @tijsrademakers, it builds now!
But for any one else stumbling on this later, I also had to enable distro profile when building since `<module>modules/flowable-spring-boot</module>` wasn't part of the default modules ...
